name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run tests
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node-version:
          - '0.8'
          - '0.10'
          - '0.12'
          - '4.x'
          - '6.x'
          - '8.x'
          - '10.x'
          - '12.x'
          - '14.x'
          - '15.x'
    runs-on: ${{matrix.os}}
    env:
      NPM_CONFIG_STRICT_SSL: ${{matrix.node-version != '0.8'}}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js ${{matrix.node-version}}
        uses: dcodeIO/setup-node-nvm@v4
        with:
          node-version: ${{matrix.node-version}}
      - name: Install latest npm
        run: |
          source /home/runner/mynvm/nvm.sh
          nvm install-latest-npm
      - name: Install dependencies
        run: |
          source /home/runner/mynvm/nvm.sh
          npm install
      - name: Run tests
        run: |
          source /home/runner/mynvm/nvm.sh
          npm test

  lint:
    name: Standard Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
            node-version: 14.x
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
